version: '3.4'

services:
  app:
    image: trackme-app
    container_name: trackme-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongo
      - postgres
    env_file:
      - .env

  mongo:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mongo
      POSTGRES_USER: mongo
      POSTGRES_PASSWORD: password
