run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    # Removed: deadcode, structcheck, varcheck (all replaced by unused)

issues:
  exclude-use-default: false