version: 2
run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  exclude-dirs:
    - third_party
    - builtin
    - examples